services:
  mongo:
    image: mongo:5.0
    container_name: aeropuerto-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    container_name: aeropuerto-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  carga-datos:
    build:
      context: .
      dockerfile: dockerfile
    container_name: aeropuerto-carga
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "scripts/cargar_datos.py"]
    restart: "no"

  django-backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: aeropuerto-django
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - MONGO_URI=mongodb://admin:admin123@mongo:27017
      - REDIS_URL=redis://redis:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aeropuerto-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - django-backend

volumes:
  mongo_data:
  redis_data:
